### ISSUE TITLE
Visual Studio 2019 - argv 

### ISSUE THREAD

**Issue by ghost** [jeremyong/cpp_nn_in_a_weekend#3]
**Hi Jeremy,**
first of all thanks for that very helpfull tutorial, I guess that you shall solve my problem immediately. 

**1.** If I run the start command from my console like that:
cd C:\Users\Sabi\Documents\Visual Studio 2019\NeuralNetwork-Cpp-02\out\build\x64-Debug (Standard)\src
nn.exe train ../../../../data/train
nn.exe evaluate ../../../../data/test ./ff.params
All is working fine without any error 
**OK**

**2.** But if I try to run it from the VS Run button with this code in main.cpp:
// Bangert eingefügt
// char* dummy_args[] = {"../../../../data/test", "evaluate", "./ff.params"};
char* dummy_args[] = {"../../../../data/test", "train", "./ff.params"};
int argc_dummy = 3;
// Bangert Ende
int main(int argc, char* argv[])
{
    // Bangert eingefügt
    argv = dummy_args;
    argc = argc_dummy;
    // Bangert Ende
.
.
.
**NOT OK**
Error in line 29 of MNIST.cpp - read_be(images, &image_count_) :
Unbehandelte Ausnahme bei 0x00007FFC3423D759 in nn.exe: Microsoft C++-Ausnahme: std::runtime_error bei Speicherort 0x00000032C56FF018
![grafik](https://user-images.githubusercontent.com/11486866/107847357-26c32f00-6deb-11eb-9d01-3816bc9c1a6b.png)

What might be the cause? I can't solve it. I guess it depends on the right expression for teh model ff params std::ios::binary
Best thanks and regards
Axel

**Comment by jeremyong** [comment]
Sorry for taking so long to get back to this. I don't have any issues running from VS, but you do have to ensure the current working directory and arguments are specified properly. As you've specified it manually, perhaps check that the executable is being emitted in the directory you think and the working directory is also set as you think? I'm going to close but feel free to open with more details if you still run into trouble
